# Generated by Django 5.2.3 on 2026-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catatan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acc', 'Disetujui'), ('tolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
