# Generated by Django 5.0.4 on 2024-04-22 10:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mitra', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(default='')),
                ('pic', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('komentar', models.CharField(max_length=100)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pengguna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('balasan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('komen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balasan', to='forum.komen')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(max_length=200)),
                ('upload_img', models.FileField(blank=True, null=True, upload_to='images/')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posting', to='forum.forum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
        migrations.AddField(
            model_name='komen',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='forum.posting'),
        ),
    ]
