# Generated by Django 5.0.4 on 2024-04-22 10:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pkl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField(default=datetime.datetime.now)),
                ('tanggal_selesai', models.DateField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time')),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('approve', models.BooleanField(default=False)),
                ('approve2', models.BooleanField(default=False)),
                ('catatan', models.TextField(help_text='maksimal 1500 karakter', max_length=1500)),
                ('reject', models.BooleanField(default=False)),
                ('reject2', models.BooleanField(default=False)),
                ('nama_dosen', models.ForeignKey(limit_choices_to={'groups__name': 'dosen'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membimbing', to=settings.AUTH_USER_MODEL)),
                ('nama_mitra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.forum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
