# Generated by Django 5.2.8 on 2026-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkl',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
